[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control"

[colors.bright]
black = "0x5b5858"
blue = "0x3fc4de"
cyan = "0x6be4e6"
green = "0x3fdaa4"
magenta = "0xf075b5"
red = "0xec6a88"
white = "0xd5d8da"
yellow = "0xfbc3a7"

[colors.normal]
black = "0x16161c"
blue = "0x26bbd9"
cyan = "0x59e1e3"
green = "0x29d398"
magenta = "0xee64ac"
red = "0xe95678"
white = "0xd5d8da"
yellow = "0xfab795"

[colors.primary]
background = "0x10131B"
foreground = "0xe0e0e0"

[cursor.style]
blinking = "Never"

[font]
size = 9.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
dynamic_title = true
opacity = 0.8

[window.padding]
x = 2
y = 2

[keyboard]
